### ISSUE TITLE
ModuleNotFoundError: No module named 'chemtok'

### ISSUE THREAD

**Issue by venti07** [ti250/cde2.1-ner-supplementary#1]
Where can i find the "chemtok" package?

cde_removed/alt_tokenizers.py --> from chemtok import ChemTokeniser

I searched on github and google but could not find it.

**Comment by ti250** [comment]
It's from [here](https://bitbucket.org/rscapplications/chemlistem/src/master/); it's a Python implementation of the OSCAR tokeniser and you can do `pip install chemlistem` to install it :)
I'll update the README to include this.
